{
 "title": "FreeRADIUS",
 "description": "FreeRADIUS dashboard for bvantagelimited/freeradius_exporter",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "Datasource", "query": "prometheus" },
   {
    "name": "job",
    "label": "Job",
    "query": {
     "query": "label_values(freeradius_up,job)"
    }
   },
   {
    "name": "instance",
    "label": "Instance",
    "query": {
     "query": "label_values(freeradius_up{job=~\"$job\"},instance)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Status", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "State",
   "type": "stat",
   "gridPos": { "h": 2, "w": 8, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max by(job) (freeradius_up{job=~\"$job\", instance=~\"$instance\"})",
     "legendFormat": "State"
    }
   ]
  },
  {
   "title": "Uptime",
   "type": "stat",
   "gridPos": { "h": 2, "w": 8, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "dtdurations" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "time() - max by(job) (freeradius_start_time{job=~\"$job\", instance=~\"$instance\"})",
     "legendFormat": "{{private_ip}}"
    }
   ]
  },
  {
   "title": "Hang up",
   "type": "stat",
   "gridPos": { "h": 2, "w": 8, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max by(job) (freeradius_start_time{job=~\"$job\", instance=~\"$instance\"} - freeradius_hup_time{job=~\"$job\", instance=~\"$instance\"})",
     "legendFormat": "Hang up"
    }
   ]
  },
  { "title": "General", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 } },
  {
   "title": "Accounting",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum by(job) (rate(freeradius_total_acct_requests{job=~\"$job\", instance=~\"$instance\"}[$__rate_interval]))",
     "legendFormat": "Requests"
    },
    {
     "expr": "sum by(job) (rate(freeradius_total_acct_responses{job=~\"$job\", instance=~\"$instance\"}[$__rate_interval]))",
     "legendFormat": "Responses"
    },
    {
     "expr": "sum by(job) (rate(freeradius_total_acct_dropped_requests{job=~\"$job\", instance=~\"$instance\"}[$__rate_interval]))",
     "legendFormat": "Dropped"
    },
    {
     "expr": "sum by(job) (rate(freeradius_total_acct_duplicate_requests{job=~\"$job\", instance=~\"$instance\"}[$__rate_interval]))",
     "legendFormat": "Duplicate"
    },
    {
     "expr": "sum by(job) (rate(freeradius_total_acct_invalid_requests{job=~\"$job\", instance=~\"$instance\"}[$__rate_interval]))",
     "legendFormat": "Invalid"
    },
    {
     "expr": "sum by(job) (rate(freeradius_total_acct_malformed_requests{job=~\"$job\", instance=~\"$instance\"}[$__rate_interval]))",
     "legendFormat": "Malformed"
    },
    {
     "expr": "sum by(job) (rate(freeradius_total_acct_unknown_types{job=~\"$job\", instance=~\"$instance\"}[$__rate_interval]))",
     "legendFormat": "Unknown"
    }
   ]
  },
  {
   "title": "Access",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum by(job) (rate(freeradius_total_access_requests{job=~\"$job\", instance=~\"$instance\"}[$__rate_interval]))",
     "legendFormat": "Requests"
    },
    {
     "expr": "sum by(job) (rate(freeradius_total_access_accepts{job=~\"$job\", instance=~\"$instance\"}[$__rate_interval]))",
     "legendFormat": "Accepts"
    },
    {
     "expr": "sum by(job) (rate(freeradius_total_access_rejects{job=~\"$job\", instance=~\"$instance\"}[$__rate_interval]))",
     "legendFormat": "Rejects"
    },
    {
     "expr": "sum by(job) (rate(freeradius_total_access_challenges{job=~\"$job\", instance=~\"$instance\"}[$__rate_interval]))",
     "legendFormat": "Challenges"
    }
   ]
  },
  {
   "title": "Authentication",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum by(job) (rate(freeradius_total_auth_responses{job=~\"$job\", instance=~\"$instance\"}[$__rate_interval]))",
     "legendFormat": "Responses"
    },
    {
     "expr": "sum by(job) (rate(freeradius_total_auth_dropped_requests{job=~\"$job\", instance=~\"$instance\"}[$__rate_interval]))",
     "legendFormat": "Dropped"
    },
    {
     "expr": "sum by(job) (rate(freeradius_total_auth_duplicate_requests{job=~\"$job\", instance=~\"$instance\"}[$__rate_interval]))",
     "legendFormat": "Duplicates"
    },
    {
     "expr": "sum by(job) (rate(freeradius_total_auth_invalid_requests{job=~\"$job\", instance=~\"$instance\"}[$__rate_interval]))",
     "legendFormat": "Invalid"
    },
    {
     "expr": "sum by(job) (rate(freeradius_total_auth_malformed_requests{job=~\"$job\", instance=~\"$instance\"}[$__rate_interval]))",
     "legendFormat": "Malformed"
    },
    {
     "expr": "sum by(job) (rate(freeradius_total_auth_unknown_types{job=~\"$job\", instance=~\"$instance\"}[$__rate_interval]))",
     "legendFormat": "Unknown"
    }
   ]
  },
  { "title": "Proxy", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 } },
  {
   "title": "Proxy Accounting",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum by(job) (rate(freeradius_total_proxy_acct_requests{job=~\"$job\", instance=~\"$instance\"}[$__rate_interval]))",
     "legendFormat": "Requests"
    },
    {
     "expr": "sum by(job) (rate(freeradius_total_proxy_acct_responses{job=~\"$job\", instance=~\"$instance\"}[$__rate_interval]))",
     "legendFormat": "Responses"
    },
    {
     "expr": "sum by(job) (rate(freeradius_total_proxy_acct_dropped_requests{job=~\"$job\", instance=~\"$instance\"}[$__rate_interval]))",
     "legendFormat": "Dropped"
    },
    {
     "expr": "sum by(job) (rate(freeradius_total_proxy_acct_duplicate_requests{job=~\"$job\", instance=~\"$instance\"}[$__rate_interval]))",
     "legendFormat": "Duplicates"
    },
    {
     "expr": "sum by(job) (rate(freeradius_total_proxy_acct_invalid_requests{job=~\"$job\", instance=~\"$instance\"}[$__rate_interval]))",
     "legendFormat": "Invalid"
    },
    {
     "expr": "sum by(job) (rate(freeradius_total_proxy_acct_malformed_requests{job=~\"$job\", instance=~\"$instance\"}[$__rate_interval]))",
     "legendFormat": "Malformed"
    },
    {
     "expr": "sum by(job) (rate(freeradius_total_proxy_acct_unknown_types{job=~\"$job\", instance=~\"$instance\"}[$__rate_interval]))",
     "legendFormat": "Unknown"
    }
   ]
  },
  {
   "title": "Proxy Access",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum by(job) (rate(freeradius_total_proxy_access_requests{job=~\"$job\", instance=~\"$instance\"}[$__rate_interval]))",
     "legendFormat": "Requests"
    },
    {
     "expr": "sum by(job) (rate(freeradius_total_proxy_access_accepts{job=~\"$job\", instance=~\"$instance\"}[$__rate_interval]))",
     "legendFormat": "Accepts"
    },
    {
     "expr": "sum by(job) (rate(freeradius_total_proxy_access_rejects{job=~\"$job\", instance=~\"$instance\"}[$__rate_interval]))",
     "legendFormat": "Rejects"
    },
    {
     "expr": "sum by(job) (rate(freeradius_total_proxy_access_challenges{job=~\"$job\", instance=~\"$instance\"}[$__rate_interval]))",
     "legendFormat": "Challenges"
    }
   ]
  },
  {
   "title": "Proxy Authentication",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum by(job) (rate(freeradius_total_proxy_auth_responses{job=~\"$job\", instance=~\"$instance\"}[$__rate_interval]))",
     "legendFormat": "Responses"
    },
    {
     "expr": "sum by(job) (rate(freeradius_total_proxy_auth_dropped_requests{job=~\"$job\", instance=~\"$instance\"}[$__rate_interval]))",
     "legendFormat": "Dropped"
    },
    {
     "expr": "sum by(job) (rate(freeradius_total_proxy_auth_duplicate_requests{job=~\"$job\", instance=~\"$instance\"}[$__rate_interval]))",
     "legendFormat": "Duplicates"
    },
    {
     "expr": "sum by(job) (rate(freeradius_total_proxy_auth_invalid_requests{job=~\"$job\", instance=~\"$instance\"}[$__rate_interval]))",
     "legendFormat": "Invalid"
    },
    {
     "expr": "sum by(job) (rate(freeradius_total_proxy_auth_malformed_requests{job=~\"$job\", instance=~\"$instance\"}[$__rate_interval]))",
     "legendFormat": "Malformed"
    },
    {
     "expr": "sum by(job) (rate(freeradius_total_proxy_auth_unknown_types{job=~\"$job\", instance=~\"$instance\"}[$__rate_interval]))",
     "legendFormat": "Unknown"
    }
   ]
  },
  { "title": "Queue", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 } },
  {
   "title": "Queue PPS",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "targets": [
    {
     "expr": "sum by(job) (freeradius_queue_pps_in{job=~\"$job\", instance=~\"$instance\"})",
     "legendFormat": "In"
    },
    {
     "expr": "sum by(job) (freeradius_queue_pps_out{job=~\"$job\", instance=~\"$instance\"}) * -1",
     "legendFormat": "Out"
    }
   ]
  },
  {
   "title": "Queue Length",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum by(job) (freeradius_queue_len_auth{job=~\"$job\", instance=~\"$instance\"})",
     "legendFormat": "Auth"
    },
    {
     "expr": "sum by(job) (freeradius_queue_len_acct{job=~\"$job\", instance=~\"$instance\"})",
     "legendFormat": "Acct"
    },
    {
     "expr": "sum by(job) (freeradius_queue_len_detail{job=~\"$job\", instance=~\"$instance\"})",
     "legendFormat": "Detail"
    },
    {
     "expr": "sum by(job) (freeradius_queue_len_proxy{job=~\"$job\", instance=~\"$instance\"})",
     "legendFormat": "Proxy"
    },
    {
     "expr": "sum by(job) (freeradius_queue_len_internal{job=~\"$job\", instance=~\"$instance\"})",
     "legendFormat": "Internal"
    }
   ]
  }
 ]
}